'use server';

import { prisma } from '@/lib/prisma';

export async function getDailySalesReport() {
  const startOfDay = new Date();
  startOfDay.setHours(0, 0, 0, 0);

  const endOfDay = new Date();
  endOfDay.setHours(23, 59, 59, 999);

  // Fetch all settled/paid orders today
  const paidOrders = await prisma.order.findMany({
    where: {
      status: 'PAID',
      updatedAt: {
        gte: startOfDay,
        lte: endOfDay,
      },
    },
    include: {
      server: true,
      items: {
        include: {
          menuItem: true,
        },
      },
    },
    orderBy: { updatedAt: 'desc' },
  });

  const totalOrders = paidOrders.length;
  const grossSales = paidOrders.reduce((acc, o) => acc + Number(o.subtotal), 0);
  const totalFoodGst = paidOrders.reduce((acc, o) => acc + Number(o.foodGst), 0);
  const totalLiquorVat = paidOrders.reduce((acc, o) => acc + Number(o.liquorVat), 0);
  const totalDiscounts = paidOrders.reduce((acc, o) => acc + Number(o.discountAmount || 0), 0);
  const netRevenue = paidOrders.reduce((acc, o) => acc + Number(o.grandTotal), 0);
  const avgOrderValue = totalOrders > 0 ? netRevenue / totalOrders : 0;

  return {
    date: new Date().toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    }),
    totalOrders,
    grossSales,
    totalFoodGst,
    totalLiquorVat,
    totalDiscounts,
    netRevenue,
    avgOrderValue,
    orders: JSON.parse(JSON.stringify(paidOrders)),
  };
}

// Alias export to prevent naming mismatches
export const getSalesReport = getDailySalesReport;

// Generate pre-formatted text payload for WhatsApp
export async function generateWhatsAppSummary() {
  const report = await getDailySalesReport();

  const text = `📊 *MAHOTSAV RESTOBAR - DAILY SALES REPORT*
📅 *Date:* ${report.date}

💰 *FINANCIAL BREAKDOWN:*
• Gross Sales: ₹${report.grossSales.toFixed(2)}
• Discounts: -₹${report.totalDiscounts.toFixed(2)}
• Food GST (5%): ₹${report.totalFoodGst.toFixed(2)}
• Liquor VAT (10%): ₹${report.totalLiquorVat.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━
🏆 *NET REVENUE: ₹${report.netRevenue.toFixed(2)}*
━━━━━━━━━━━━━━━━━━━━

📈 *OPERATIONAL METRICS:*
• Total Settled Bills: ${report.totalOrders}
• Average Ticket Value: ₹${report.avgOrderValue.toFixed(2)}

_Generated by Mahotsav Restobar POS Terminal_`;

  return { text, report };
}